In [2]:
import pandas as pd

In [3]:
books_df = pd.read_csv("../project_info/books.csv")

In [4]:
books_df.describe()

             bookID  ratings_count  text_reviews_count
count  11127.000000   1.112700e+04        11127.000000
mean   21310.938887   1.793649e+04          541.864474
std    13093.358023   1.124794e+05         2576.174610
min        1.000000   0.000000e+00            0.000000
25%    10287.000000   1.040000e+02            9.000000
50%    20287.000000   7.450000e+02           47.000000
75%    32104.500000   4.993500e+03          237.500000
max    45641.000000   4.597666e+06        94265.000000

In [5]:
books_df.tail()

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher,Unnamed: 12
11122,45631,Expelled from Eden: A William T. Vollmann Reader,William T. Vollmann/Larry McCaffery/Michael He...,4.06,1560254416,9.78E+12,eng,512,156,20,12/21/2004,Da Capo Press,NaN
11123,45633,You Bright and Risen Angels,William T. Vollmann,4.08,140110879,9.78E+12,eng,635,783,56,12/01/1988,Penguin Books,NaN
11124,45634,The Ice-Shirt (Seven Dreams #1),William T. Vollmann,3.96,140131965,9.78E+12,eng,415,820,95,08/01/1993,Penguin Books,NaN
11125,45639,Poor People,William T. Vollmann,3.72,60878827,9.78E+12,eng,434,769,139,2/27/2007,Ecco,NaN
11126,45641,Las aventuras de Tom Sawyer,Mark Twain,3.91,8497646983,9.79E+12,spa,272,113,12,5/28/2006,Edimat Libros,NaN

In [6]:
books_df

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher,Unnamed: 12
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,439785960,9.78E+12,eng,652,2095690,27591,9/16/2006,Scholastic Inc.,NaN
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,439358078,9.78E+12,eng,870,2153167,29221,09/01/2004,Scholastic Inc.,NaN
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,439554896,9.78E+12,eng,352,6333,244,11/01/2003,Scholastic,NaN
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9.78E+12,eng,435,2339585,36325,05/01/2004,Scholastic Inc.,NaN
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,439682584,9.78E+12,eng,2690,41428,164,9/13/2004,Scholastic,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11122,45631,Expelled from Eden: A William T. Vollmann Reader,William T. Vollmann/Larry McCaffery/Michael He...,4.06,1560254416,9.78E+12,eng,512,156,20,12/21/2004,Da Capo Press,NaN
11123,45633,You Bright and Risen Angels,William T. Vollmann,4.08,140110879,9.78E+12,eng,635,783,56,12/01/1988,Penguin Books,NaN
11124,45634,The Ice-Shirt (Seven Dreams #1),William T. Vollmann,3.96,140131965,9.78E+12,eng,415,820,95,08/01/1993,Penguin Books,NaN
11125,45639,Poor People,William T. Vollmann,3.72,60878827,9.78E+12,eng,434,769,139,2/27/2007,Ecco,NaN
11126,45641,Las aventuras de Tom Sawyer,Mark Twain,3.91,8497646983,9.79E+12,spa,272,113,12,5/28/2006,Edimat Libros,NaN

In [ ]:
books_df.language_code.describe()

count     11127
unique       28
top         eng
freq       8908
Name: language_code, dtype: object

In [8]:
books_df[books_df.language_code == "eng"].describe()

             bookID  ratings_count  text_reviews_count
count   8908.000000   8.908000e+03         8908.000000
mean   21091.059722   2.157027e+04          645.156601
std    13018.487243   1.252089e+05         2862.872984
min        1.000000   0.000000e+00            0.000000
25%    10033.750000   1.410000e+02           11.000000
50%    19791.000000   1.001000e+03           59.000000
75%    31962.000000   6.575750e+03          300.000000
max    45639.000000   4.597666e+06        94265.000000

In [9]:
books_df[books_df.language_code == "en-US"].describe()

             bookID  ratings_count  text_reviews_count
count   1408.000000     1408.00000         1408.000000
mean   22448.262784     3773.90696          160.357244
std    13320.303266    11856.59848          454.279541
min        9.000000        1.00000            0.000000
25%    11191.500000      116.75000           11.000000
50%    22494.000000      529.50000           35.500000
75%    33161.250000     2207.00000          124.000000
max    45630.000000   191577.00000         8119.000000

In [10]:
books_df[books_df.language_code == "fre"].describe()

             bookID  ratings_count  text_reviews_count
count    144.000000     144.000000          144.000000
mean   20325.159722    3277.319444           64.513889
std    11553.433961   19268.941350          248.435665
min       80.000000       0.000000            0.000000
25%    11975.750000       6.000000            1.000000
50%    18074.000000      32.500000            2.000000
75%    27771.500000     195.500000           15.250000
max    45531.000000  178403.000000         2088.000000

In [11]:
books_df.title

0        Harry Potter and the Half-Blood Prince (Harry ...
1        Harry Potter and the Order of the Phoenix (Har...
2        Harry Potter and the Chamber of Secrets (Harry...
3        Harry Potter and the Prisoner of Azkaban (Harr...
4        Harry Potter Boxed Set  Books 1-5 (Harry Potte...
                               ...
11122     Expelled from Eden: A William T. Vollmann Reader
11123                          You Bright and Risen Angels
11124                      The Ice-Shirt (Seven Dreams #1)
11125                                          Poor People
11126                          Las aventuras de Tom Sawyer
Name: title, Length: 11127, dtype: str